repos:
  -   repo: https://github.com/commitizen-tools/commitizen
      rev: v3.13.0
      hooks:
        - id: commitizen
          stages: [commit-msg]
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
  -   repo: https://github.com/hhatto/autopep8
      rev: v2.0.4
      hooks:
      -   id: autopep8
  -   repo: https://github.com/psf/black
      rev: 24.2.0
      hooks:
      -   id: black
          args: [--line-length=79]
  -   repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
      -   id: flake8
          args: ['--ignore=E129,E501']
